

services:
  postgres:
    image: postgres:15
    container_name: PostgresContainer
    environment:
      POSTGRES_DB: my-postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - my-network

  app:
    image: filemanager:1.0.0.R
    container_name: FileManagerContainer
    environment:
      RDS_HOSTNAME: postgres
      RDS_PORT: 5432
      RDS_DB_NAME: my-postgres
      RDS_USERNAME: postgres
      RDS_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - my-network

networks:
  my-network:
    driver: bridge



#
#services:
#  app:
#    image: filemanager:0.0.7.A
#    container_name: FileManagerContainer
#    environment:
#      RDS_HOSTNAME: localhost
#      RDS_PORT: 5432
#      RDS_DB_NAME: my-postgres
#      RDS_USERNAME: postgres
#      RDS_PASSWORD: root
#    ports:
#      - "8080:8080"
#    networks:
#      - my-network
#
#networks:
#  my-network:
#    driver: bridge









